# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.7
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    #-- Generic checks.
        # Check for files that would conflict in case-insensitive filesystems.
    -   id: check-case-conflict
        # Check for files that contain merge conflict strings.
    -   id: check-merge-conflict
        # Checks for symlinks which do not point to anything.
    -   id: check-symlinks
        # Prevent giant files from being committed.
    -   id: check-added-large-files

    #-- Content specific checks.
        # Trims trailing whitespace.
    -   id: trailing-whitespace
        exclude: ^tests/data/
        # Ensures that a file is either empty, or ends with one newline.
    -   id: end-of-file-fixer
        exclude: ^tests/data/
        # Replaces or checks mixed line ending.
    -   id: mixed-line-ending
        exclude: ^tests/data/
        args: [--fix=lf]
        #  Detects the presence of private keys.
    -   id: detect-private-key
        # Checks yaml files for parseable syntax.
    -   id: check-yaml

    #-- Python specific checks.
        # Require literal syntax when initializing empty or zero Python builtin
        # types.
    -   id: check-builtin-literals
        # Checks a common error of defining a docstring after code.
    -   id: check-docstring-first
        # Check for debugger imports and py37+ `breakpoint()` calls in python
        # source.
    -   id: debug-statements
        # This hook replaces double quoted strings with single quoted strings.
    -   id: double-quote-string-fixer
        # This verifies that test files are named correctly.
    -   id: name-tests-test
        args: ['--django']

-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.29.0
    hooks:
        # Runs python file formatter.
    -   id: yapf

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
        # Runs flake8, a python linter.
        # Run this after yapf, since that fixes some lint problems already.
    -   id: flake8
